DROP IF EXISTS user;
DROP IF EXISTS quote;


CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password TEXT NOT NULL
);


CREATE TABLE article(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(80) UNIQUE NOT NULL,
    content TEXT NOT NULL
    FOREIGN KEY (author_id) REFERENCES user (id)
    ON DELETE CASCADE
);